language: elixir

branches:
  only:
    - "master"

cache:
  directories:
    - deps
    - _build

otp_release:
  - 20.2
elixir:
  - 1.6.4

dist: trusty
sudo: required
services:
  - docker

before_script:
  - IP_IFACE=eth0 ./ci/docker_up.sh
script:
  - mkdir -p priv/repo/migrations
  - MIX_ENV=test mix deps.compile
  - mix test
  - MIX_ENV=test travis_wait mix dialyzer
